camera:
    # Publish all joint states -----------------------------------
  camera_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10
    
  camera_base_controller:
    type: effort_controllers/JointPositionController
    joint: rotate
    pid: {p: 50.0, i: 0.2, d: 0.3}

  camera_depth_controller:
    type: effort_controllers/JointPositionController
    joint: depth
    pid: {p: 50.0, i: 0.2, d: 0.3}
    
  camera_height_controller:
    type: effort_controllers/JointPositionController
    joint: height
    pid: {p: 50.0, i: 0.2, d: 0.3}
    
  camera_tilt_controller:
    type: effort_controllers/JointPositionController
    joint: tilt
    pid: {p: 50.0, i: 0.2, d: 0.3}
    
