braccio_arm:
    # Publish all joint states -----------------------------------
  braccio_arm_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10
    
  base_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_joint
    pid: {p: 5.0, i: 0.2, d: 0.01}

  shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 5.0, i: 0.2, d: 0.1}
    
  elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 5.0, i: 0.2, d: 0.01}
    
  wrist_pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_pitch_joint
    pid: {p: 5.0, i: 0.2, d: 0.01}
    
  wrist_roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_roll_joint
    pid: {p: 5.0, i: 0.2, d: 0.01}
   
  gripper_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_joint
    pid: {p: 200.0, i: 0.2, d: 0.2} 
    
  sub_gripper_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: sub_gripper_joint
    pid: {p: 200.0, i: 0.2, d: 0.2}        
    
  camera_rotate_controller:
    type: effort_controllers/JointPositionController
    joint: camera_rotate
    pid: {p: 50.0, i: 0.2, d: 0.3}

  camera_depth_controller:
    type: effort_controllers/JointPositionController
    joint: camera_depth
    pid: {p: 50.0, i: 0.2, d: 0.3}
    
  camera_height_controller:
    type: effort_controllers/JointPositionController
    joint: camera_height
    pid: {p: 50.0, i: 0.2, d: 0.3}
    
  camera_tilt_controller:
    type: effort_controllers/JointPositionController
    joint: camera_tilt
    pid: {p: 50.0, i: 0.2, d: 0.3}
        
